@component('mail::message')
# Feedback Request for Your Booking

Hello {{ $booking->customer_name }},

We hope you enjoyed your recent visit to {{ $booking->salon->name }}. Your feedback is important to us.

**Booking Details:**
- **Date:** {{  Carbon\Carbon::parse($booking->reservation_date)->format('M d, Y') }}
- **Time:** {{ $booking->reservation_time ?? 'Not specified' }}

Please take a moment to provide your valuable feedback about your experience.

@component('mail::button', ['url' => route('website.salon.view', ['uuid' => $booking->salon->uuid, '#commentForm']), 'color' => 'blue'])
Provide Feedback
@endcomponent

Thank you,<br>
{{ config('app.name') }}

@component('mail::subcopy')
    This email was automatically generated by the {{ config('app.name', 'YoHairHub') }} Reservation System. Please do not reply to this email.
@endcomponent
@endcomponent
