@component('mail::message')
# Booking Confirmed

Hello {{ $booking->customer_name }},

We are pleased to confirm your booking at {{ $booking->salon->name }}.

**Booking Details:**
- **Date:** {{ Carbon\Carbon::parse($booking->reservation_date)->format('M d, Y') }}
- **Time:** {{ $booking->reservation_time ?? 'Not specified' }}

If you have any questions or need to make changes, please contact us.

Thank you for choosing {{ $booking->salon->name }}!

@component('mail::subcopy')
    This email was automatically generated by the {{ config('app.name', 'YoHairHub') }} Reservation System. Please do not reply to this email.
@endcomponent
@endcomponent
